apiVersion: v1
kind: Pod
metadata:
  name: intruso
  namespace: producao
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: intruso
      image: ghcr.io/amandafo/api-pagamentos:v1.0.1
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
  restartPolicy: Never
