apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pagamentos
  namespace: producao
  labels:
    app.kubernetes.io/name: api-pagamentos
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-pagamentos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-pagamentos
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/amandafo/api-pagamentos@sha256:SUBSTITUIR_PELO_DIGEST
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: api-pagamentos
  namespace: producao
spec:
  selector:
    app.kubernetes.io/name: api-pagamentos
  ports:
    - name: http
      port: 80
      targetPort: http
